### ISSUE TITLE
import should be toCollection

### ISSUE THREAD

**Issue by rconfig** [Maatwebsite/laravel-excel-docs#31]
In collections.md

Should 
"Excel::import(new UsersImport, 'users.xlsx');"
be
"Excel::ToCollection(new UsersImport, 'users.xlsx');"

To produce a collection output, instead of a DB import?

**Comment by patrickbrouwers** [comment]
No, example is correct. Needs to be import, so collection method in import is being called.

**Comment by nickpoulos** [comment]
I would tend to agree with this suggestion, or some other system.  Right now it is not intuitive at all how this system is supposed to work,  and not documented well enough to alleviate the lack of intuition.  In the v3 branches, I am confused as to what the point of a ToCollection concern is exactly? 

I tried to setup a very simple toCollection import. I don't want the items actually stored in a database at the time of Excel file reading because I need to sum and run calculations on the data first, then pass it off to other objects that actually handle the importing and logging.  I don't want a mega import class. 
So I setup a simple Import using the toCollection concern, like so: 

```
<?php

namespace App\Services\Revenue\ExcelImports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;

class KargoImport implements ToCollection
{
    public function collection(Collection $rows)
    {
        return $rows->transform(function($row) {
           return [
               'date' => $row[0],
               'site' => $row[1],
               'impressions' => $row[2],
               'revenue' => $row[3]
           ];
        });
    }
}
```

Then I tried to import using:

```
$records = Excel::import(new KargoImport(), $filePath);
```

Which returns a MaatWebsiteExcel object that I can't seem to access the collection of data as hoped.  And not even that, I stuck a DD in my collection() method of KargoImport, and the function doesn't even get hit? 

So instead I tried:

```
$records = Excel::toCollection(new KargoImport(), $filePath);
```
That at least returned my data, but again,  it was not run through the collections() function at all.

I get the same exact results when I pass in a null importer like so:

```
$records = Excel::toCollection(null, $filePath);
```

So that tells me for my purposes, the Importer is useless.  But it doesn't seem it should be? I would think the first example, using the Excel::import() function with a ToCollection importer as param, would return the collection of rows already run through the Importer->collection() method.  This would also allow me to use the other functions/traits for chunking reads and other functionality.
